blueprints/communities/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user, logout_user, login_required
from blueprints.communities.forms import *
from data_access.models import user_account, user_information, proposal_tracker, event_information, community_member, community_info, event_participation, referral, event_attachment, user_photo
from data_access.queries import user_views, linkage_views, community_views, event_views

from static.email import send_email
from extensions import db, bcrypt
from datetime import datetime

import os

communities = Blueprint('communities', __name__, template_folder="templates")

APP_ROOT = os.path.dirname(os.path.abspath(__file__))

@communities.before_request
def before_request():

	if current_user.is_authenticated and not current_user.is_anonymous:
		if current_user.type == 1:
			return redirect(url_for('admin.index'))
		elif current_user.type == 2:
			return redirect(url_for('registered.index'))
		elif current_user.type == 3:
			return redirect(url_for('linkages.index'))
		elif current_user.type == 5:
			return redirect(url_for('religious_admin.index'))
		user_account.logout()
		
@communities.route('/communities')
@login_required
def index():

	photo = user_photo.photo(current_user.info_id)

	return render_template('/communities/index.html', title="Home", photo=photo, active='home')

@communities.route('/communities/events/<status>/search_<search>.page_<page>', methods=['GET', 'POST'])
@login_required
def events(status, page, search):

	if status=='scheduled':
		value='S'
	elif status=='new':
		value='N'
	elif status=='finished':
		value='F'
	else:
		value=status

	events = event_views.community_events([value, search, page, current_user.info_id])

	photo = user_photo.photo(current_user.info_id)

	form = SearchForm()

	if form.validate_on_submit():

		return redirect(url_for('communities.events', status=status, page='1', search=form.search.data))

	return render_template('/communities/events/index.html', title="Events", form=form, events=events, status=status, search=search, photo=photo, active='events')

@communities.route('/communities/events/calendar', methods=['GET', 'POST'])
@login_required
def events_calendar():

	photo = user_photo.photo(current_user.info_id)

	events = event_information.calendar()
	
	return render_template('/communities/events/index-calendar.html', title="Events", events=events, photo=photo, active='events')
	
@communities.route('/communities/events/show/id=<id>')
@login_required
def event_participants(id):

	event = event_views.show_info(id)
	participants = community_views.event_participants(id)
	joined = event_participation.show_joined(id)

	form = SearchForm()

	return render_template('/communities/events/add_participants.html', title= event.name.title() , event = event, participants=participants, joined=joined, form=form, active='events')

@communities.route('/communities/event_<id>/<action>/<participant>')
@login_required
def participant_action(id, action, participant):

	if action=='add':

		record = event_participation.show_status([id, participant])

		if record is None:
			value = [None, id, participant, 'N']
			event_participation.add(value)
		else:
			value = [id, participant, 'J']
			event_participation.update(value)

		flash('Member added to event!', 'success')

	elif action=='remove':

		value = [id, participant, 'R']
		event_participation.update(value)
		flash('Member removed from event!', 'success')

	return redirect(url_for('communities.event_participants',id=id))

@communities.route('/communities/members/search_<search>', methods=['GET', 'POST'])
@login_required
def members(search):

	members = community_views.members_list(search)

	photo = user_photo.photo(current_user.info_id)

	form = SearchForm()

	if form.validate_on_submit():

		return redirect(url_for('communities.members', search=form.search.data))

	return render_template('/communities/members/index.html', title="Members", members=members, form=form, search=search, photo=photo,  active='members')

@communities.route('/communities/members/add', methods=['GET', 'POST'])
@login_required
def member_add():

	form = AddMemberForm()

	if form.validate_on_submit():

		for_company = user_views.profile_info(current_user.info_id)

		value = [
			None,form.firstname.data, form.middlename.data, form.lastname.data, 
			for_company.company_name, None, form.gender.data, form.birthday.data,
			form.address.data, form.telephone.data, form.mobile.data, 0
			]

		user_information.add(value)

		user_id = user_information.reserve_id()

		if form.occupation.data=='':
			occupation=None
		else:
			occupation=form.occupation.data

		value = [None, user_id, current_user.info_id, occupation, form.income.data, form.religion.data, "A"]

		community.add(value)

		flash('Member added!', 'success')
		return redirect(url_for('communities.members', search=' '))

	return render_template('/communities/members/add.html', title="Add Member", form=form, active='members')

@communities.route('/communities/members/update/id=<id>', methods=['GET', 'POST'])
@login_required
def member_updateinfo(id):

	user = community.retrieve_member(id)
	member = user_information.linkage_info(user.member_id)

	form = UpdateMemberForm()

	if form.validate_on_submit():

		member.first_name = form.firstname.data
		member.middle_name = form.middlename.data
		member.last_name = form.lastname.data
		member.gender = form.gender.data
		member.birthday = form.birthday.data
		user.occupation = form.occupation.data
		user.income = form.income.data
		user.religion = form.religion.data
		member.address = form.address.data
		member.telephone = form.telephone.data
		member.mobile_number = form.mobile.data

		db.session.commit()

		flash('Member updated!', 'success')

		return redirect(url_for('communities.members', search=' '))

	else:

		form.firstname.data = member.first_name
		form.middlename.data = member.middle_name
		form.lastname.data = member.last_name
		form.gender.data = member.gender
		form.birthday.data = member.birthday
		form.occupation.data = user.occupation
		form.income.data = user.income
		form.religion.data = user.religion
		form.address.data = member.address
		form.telephone.data = member.telephone
		form.mobile.data = member.mobile_number

	return render_template('/communities/members/update.html', title="Update Member", form=form, active='members')

@communities.route('/communities/members/action/id=<id>')
@login_required
def member_action(id):

	user = community.retrieve_member(id)
	member = user_information.linkage_info(user.member_id)

	if user.status == "A":

		status = "D"
		flash(member.first_name.title() + " was disabled!", "success")

	elif user.status == "D":

		status = "A"
		flash(member.first_name.title() + " was activated!", "success")

	community.update_status(user.id, status)

	return redirect(url_for('communities.members', search=' '))

@communities.route('/communities/linkages/search_<search>.page_<page>', methods=['GET', 'POST'])
@login_required
def linkages(page, search):

	linkages = linkage_views.show_list(['A', search, 3, page])

	photo = user_photo.photo(current_user.info_id)

	form = SearchForm()

	if form.validate_on_submit():

		return redirect(url_for('communities.linkages', page='1', search=form.search.data))

	return render_template('/communities/linkages/index.html', title="Linkages", form=form, linkages=linkages, page=page, search=search, photo=photo, active='linkages')

@communities.route('/communities/communities/search_<search>.page_<page>', methods=['GET', 'POST'])
@login_required
def communities_show(page, search):

	communities = linkage_views.show_list(['A',search, 4, page])

	photo = user_photo.photo(current_user.info_id)

	form = SearchForm()

	if form.validate_on_submit():

		return redirect(url_for('communities.communities_show', page='1', search=form.search.data))

	return render_template('/communities/communities/index.html', title="Communities", form=form, communities=communities, search=search, photo=photo, active='communities')

@communities.route('/communities/referral', methods=['GET', 'POST'])
@login_required
def referral_users():

	form = ReferralForm()

	if form.validate_on_submit():

		html = 'asdlkfjasfd'
		subject = 'REFFERAL: '
		admin = user_account.retrieve_user(1)

		email_parts = [html, subject, admin.email_address, form.email.data, None]
		send_email(email_parts)

		value = [None, current_user.id, form.name.data, form.email.data, form.type.data, 'N']

		referral.add(value)

		flash('Referral has been sent!', 'success')
		return redirect(url_for('communities.referral_users'))	

	return render_template('/communities/referral/index.html', title="Referral", form=form)

@communities.route('/communities/contactus')
@login_required
def contactus():

	photo = user_photo.photo(current_user.info_id)

	return render_template('/communities/contactus/index.html', title="Contact Us", photo=photo)

@communities.route('/communities/termsandconditions')
@login_required
def termsandconditions():

	photo = user_photo.photo(current_user.info_id)

	return render_template('/communities/termsandconditions/index.html', title="Terms and Conditions", photo=photo)

@communities.route('/communities/profile/about|<user>', methods=['GET', 'POST'])
@login_required
def profile_about(user):

	communities = user_views.profile_info(current_user.info_id)
	photo = user_photo.photo(current_user.info_id)
	form = PictureForm()

	if form.validate_on_submit():

		file = form.photo.data
		old, extension = os.path.splitext(file.filename)
		filename = str(current_user.info_id)+extension
		file_path = 'static/photos/profiles/' + filename

		file.save(file_path)

		if photo:
			user_photo.update([current_user.info_id, file_path])
		else:
			user_photo.add([None, current_user.info_id, file_path])

		flash('Profile picture has been updated!', 'success')
		return redirect(url_for('communities.profile_about', user=user))

blueprints/communities/templates/communities/events/_events.html
	<div class="column is-one-quarter">
		<div class="card select-list has-text-centered">
			<div class="card-content">
				<div class="level">
					<div class="level-item">
						<img class="image is-128x128" src="../../../static/images/event-default.png">
					</div>
				</div>

	      		<div class="title is-5">{{ event.name }}</div>
	      		<p class="subtitle is-6">
	      			<i class="fas fa-calendar"></i>&nbsp; {{event.event_date.strftime('%B %e, %Y')}}</br>
					<i class="fas fa-map-marker-alt"></i>&nbsp; {{ event.location }}
				</p>
	      		
	      		<div class="button event-btn" onclick="show_event('{{event.id}}')">More Details</div>
			</div>
		</div>
	</div>

	<div id={{event.id}}_modal class="modal">
  		<div class="modal-background"></div>
  			<div class="modal-card">
    			<header class="modal-card-head">
      				<p class="modal-card-title"></p>
      				<button class="delete" onclick="close_event('{{event.id}}')"></button>
				</header>
				<div class="overlay-card-modal has-text-centered">
			    	<div class="modal-media">
			            <article class="media">
			              	<figure class="media-left">
				                <div class="circular-event-modal">
				                	<img src="../../../static/images/event-default.png">
				                </div>
			              	</figure>
			              	<div class="media-content">
			                	<div class="content modal-text has-text-centered">
				                	<p class="title is-size-4">{{event.name}}</p>
				                	<i class="icon fas fa-calendar-alt"></i>{{event.event_date.strftime('%B %e, %Y')}}<br>
			                		<span class="tag status-tag is-medium">
				                		{% if event.event_status=='S' %}
									    		Scheduled
									    	{% else %}
									    		Finished
									    {% endif %}
				                	</span>
			                	</div>
			              </div>
			            </article>
			        </div>
			    </div>
    			<section class="modal-card-body">
	    			<div class="container modal-show" id="info_div">
				      	<div class="card">
							<header class="card-header has-background-light">
							    <p class="card-header-title">
							    	Event Information
							    </p>
						  	</header>
						  	<div class="card-content show-modal">
							    <div class="panel-block">
								    <article class="media">
									  	<figure class="media-left">
									  		<span><i class="fas fa-building prof-panel-icon"></i></span>
									    	<p>Organizer</p>
									  	</figure>
									  	<div class="media-content">
									    	<div class="content">
									      		<p>
									        		<strong>{{event.company_name}}</strong>
									      		</p>
									    	</div>
									  	</div>
									</article>
								</div>
							    <div class="panel-block">
								    <article class="media">
									  	<figure class="media-left">
									  		<span><i class="fas fa-newspaper prof-panel-icon"></i></span>
									    	<p>Description</p>
									  	</figure>
									  	<div class="media-content">
									    	<div class="content">
									      		<p>
									        		<strong>{{event.description}}</strong>
									      		</p>
									    	</div>
									  	</div>
									</article>
								</div>
							    <div class="panel-block">
								    <article class="media">
									  	<figure class="media-left">
									  		<span><i class="fas fa-exclamation prof-panel-icon"></i></span>
									    	<p>Objective</p>
									  	</figure>
									  	<div class="media-content">
									    	<div class="content">
									      		<p>
									        		<strong>{{event.objective}}</strong>
									      		</p>
									    	</div>
									  	</div>
									</article>
								</div>
							    <div class="panel-block">
								    <article class="media">
									  	<figure class="media-left">
									  		<span><i class="fas fa-map-marker-alt prof-panel-icon"></i></span>
									    	<p>Location</p>
									  	</figure>
									  	<div class="media-content">
									    	<div class="content">
									      		<p>
									        		<strong>{{event.location}}</strong>
									      		</p>
									    	</div>
									  	</div>
									</article>
								</div>
							    <div class="panel-block">
								    <article class="media">
									  	<figure class="media-left">
									  		<span><i class="fas fa-calendar-alt prof-panel-icon"></i></span>
									  		<p>{% if event.status!='A' %}
									    	Target Date
									    	{% else %}
									    	Date
									  		{% endif %}</p>
									  	</figure>
									  	<div class="media-content">
									    	<div class="content">
									      		<p>
									        		<strong>{{event.event_date.strftime('%B %e, %Y')}}</strong>
									      		</p>
									    	</div>
									  	</div>
									</article>
								</div>
							    <div class="panel-block">
								    <article class="media">
									  	<figure class="media-left">
									  		<span><i class="fas fa-clipboard-list prof-panel-icon"></i></span>
									  		<p>Thrust</p>
									  	</figure>
									  	<div class="media-content">
									    	<div class="content">
									      		<p>
									        		<strong>
									        			{% if event.thrust==1 %}
									        				Educational
									        			{% elif event.thrust==2 %}
									        				Environmental
									        			{% elif event.thrust==3 %}
									        				Health
									        			{% elif event.thrust==4 %}
									        				Livelihood
									        			{% elif event.thrust==5 %}
									        				Socio-Political
									        			{% elif event.thrust==6 %}
									        				Spiritual   
									        			{% endif %}
									        		</strong>
									      		</p>
									    	</div>
									  	</div>
									</article>
								</div>
							</div>
						</div>
				    </div>
		  		</section>
	    		<footer class="modal-card-foot buttons is-right">
	    			{% if event.event_status=='S' %}
	    			<a class="button is-info" href="{{url_for('communities.event_participants',id=event.id)}}"><i class="fas fa-users"></i>&nbsp;Participants</a>
	    			<button class="button is-warning" onclick="show_location('{{event.id}}')"><span class="fa fa-map"></span>&nbsp;Location</button>
	    			{% endif %}
	    		</footer>
  			</div>
	</div>
	<div id={{event.id}}_location class="modal">
  		<div class="modal-background"></div>
  			<div class="modal-card">
    			<header class="modal-card-head">
      				<p class="modal-card-title has-text-white">{{event.name}} Location</p>
      				<button class="delete" onclick="close_location('{{event.id}}')"></button>
    			</header>
	    		<section class="modal-card-body">
	  				<div class="mapouter">
						<div class="gmap_canvas">
							<iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q={{event.location}}&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
						</div>
					</div>
	      		</section>
    	
	    		<footer class="modal-card-foot buttons is-right">

	    		</footer>
	  		</div>
	</div>

blueprints/communities/templates/communities/events/_participants.html
								<tbody>
									<tr class="table-row">
									    <td>{{ participant.name }}</td>
									    <td>{{ participant.address }}</td>
									    {% if participant.occupation == '' %}
									   	<td>Not employed</td>
									    {% else %}
									    <td>{{ participant.occupation }}</td>
									    {% endif %}
									    <td>{{ participant.religion }}</td>
										<td>
											<a class="button is-warning tooltip" href="{{url_for('communities.event_participants', id = event.id)}}" data-tooltip="View">
												<span class="icon">
													<i class="fa fa-eye"></i>
												</span>
											</a>
											{% if joined < event.participant_no %}
												{% if participant.status=='A' or participant.status=='R' %}
													<a class="button is-success tooltip" href="{{url_for('communities.participant_action', id = event.id, action='add', participant=participant.id)}}" data-tooltip="Add" href="">
														<span class="icon">
															<i class="fa fa-plus"></i>
														</span>
													</a>
													{% elif participant.status=='J' %}
													<a class="button is-danger tooltip" href="{{url_for('communities.participant_action', id = event.id, action='remove', participant=participant.id)}}" data-tooltip="Remove" href="">
														<span class="icon">
															<i class="fa fa-times"></i>
														</span>
													</a>
													{% endif %}
											{% else %}
											 		{% if participant.status=='J' %}
													<a class="button is-danger tooltip" href="{{url_for('communities.participant_action', id = event.id, action='remove', participant=participant.id)}}" data-tooltip="Remove" href="">
														<span class="icon">
															<i class="fa fa-times"></i>
														</span>
													</a>
											 		{% endif %}
											{% endif %}
										</td>
									</tr>	
								</tbody>

blueprints/communities/templates/communities/events/add_participants.html
{% extends "communities-base.html" %}

{% block content %} 

			<div class="notification gold">
				<div class="columns is-left">
					<div class="column view-icons">
						<article class="media">
						  	<figure class="media-left"> 
						  		<a class="button add" href="{{url_for('communities.events', page='1', status='all', search=' ')}}" ><i class="fas fa-arrow-alt-circle-left"> </i>&nbsp Back</a>
						  	</figure>
						  	<figure class="media-left"> 
						  		<span class='button add'>{{event.name}}</span>
						  		<p>Slots: {{joined}}/{{event.participant_no}}</p>
						  	</figure>
						</article>
					</div>
					<div class="column search-box">
						<div class="field is-pulled-right has-addons has-addons-centered">
							<div class="control">
								<form action="" method="POST">
								{{form.hidden_tag()}}
							    	{{form.search(class_='input', placeholder='Search')}}
							</div>
							<p class="control">
						     	{{form.submit(class_='button search')}}
							</p>
							</form>
						</div>
					</div>
				</div>
			</div>

			<div class="columns is-gapless">

				<div class="column">
					<div class="card list">
						<div class="card-header">
							<p class="card-header-title">
							<span class="fas fa-poll-h"></span>&nbsp;
							Qualified Members
							</p>
							<div class="is-pulled-right">
								<p class="card-header-title">
									Total: {{participants|length}}
								</p>
							</div>
						</div>
						<div class="card-content">
							<div class="table-responsive">
								<table class="table is-striped is-fullwidth is-hoverable">
								{% if participants %}
								<thead>
									<tr>
									    <th class="newlist">Name</th>
									    <th class="newlist">Address</th>
									    <th class="newlist">Occupation</th>
									    <th class="newlist">Religion</th>
									    <th class="newlist hidedesktop">Actions</th>
									 </tr>
									
								</thead>

									{% for participant in participants %}
											{% include 'communities/events/_participants.html' %}
									{% endfor %}

								{% else %}

								<tbody>

									<tr class = "table-row">
										<td class = "has-text-centered">---Nothing to show---</td>
								 	</tr>
									
								</tbody>

								{% endif %}
							</table>
							</div>
						</div>
					</div>
				</div>
			</div>


{% endblock %}

blueprints/communities/templates/communities/events/index-calendar.html
{% extends "communities-base.html" %}

{% block content %}

			<div class="notification gold">
				<div class="columns is-centered">
					<div class="column view-icons">
						<article class="media">
						  	<figure class="media-left"> 
						  		<a class="button viewbtn" href="{{url_for('communities.events',status='all', page='1', search=' ')}}">
									<span class="icon">
										<i class="fa fa-list"></i>
									</span>
								</a>
								<a class="button viewbtn is-active" href="{{url_for('communities.events_calendar')}}">
									<span class="icon">
										<i class="fa fa-calendar-alt"></i>
									</span>
								</a>
						  	</figure>
						</article>
					</div>
				</div>
			</div>

			<div class="column">
				<div class="card box">

					<hr class="is-marginless">
					<div class="card-content">
						<div class="table-responsive">
							<table class="table is-hoverable is-fullwidth" id = "event">

								{% if events %}
								<tbody>

									<tr class = "table">
										<td>
										<table class = "table is-bordered is-hoverable is-fullwidth">
											<tr class="table-row">

												<td colspan="1" id="prev">
													<button class = "button backbtnprof is-small" id="prev" onclick="prev_next(this.id)">
														<i class="fas fa-arrow-left"></i>
													</button>
												</td>

												<td colspan="5" id="month_year" style = "text-align:center"></td>

												<td colspan="1" id="next">
													<button class = "button backbtnprof is-small is-pulled-right" id="next" onclick="prev_next(this.id)">
														<i class="fas fa-arrow-right"></i>
													</button>
												</td>

											</tr>	

											<tr class="table-row">

												<td width = "14%">Sun</td>
												<td width = "14%">Mon</td>
												<td width = "14%">Tue</td>
												<td width = "14%">Wed</td>
												<td width = "14%">Thu</td>
												<td width = "14%">Fri</td>
												<td width = "14%">Sat</td>

											</tr>
										</table>
										</td>
									</tr>

									<tr class = "table-row">

										<td colspan = 7 id = "calendar"> </td>


									</tr>	

								</tbody>

							</table>
						</div>


						<script>

							function Calendar(min, max, month, year){

								var table = document.createElement('table')
								var last = max.getDate()
								var start_day = min.getDay()
								var day=1
								var sw = 0
								var mark=0

								table.className ="table is-bordered is-fullwidth"

								while(day<=last){

									var tr = document.createElement('tr')

										for (col=0; col<=6; col++){
											
											var td = document.createElement('td')
											td.style.width= "14%"

											if (today.getDate()==day && today.getMonth()+1==month && today.getFullYear()==year){
												td.innerHTML='<span class="tag is-black is-small is-rounded">'+ day +'</span>'
											}
											else{
												td.innerHTML=day												
											}

											url=''
											name = ''

											{% for event in events %}

												if ({{event.event_date.strftime('%e')}}==day && {{event.event_date.strftime('%m')}}==month && {{event.event_date.strftime('%Y')}}==year){
													name = '{{event.name}}<br>'
													url = ""
													td.innerHTML= td.innerHTML + '<br><a href = "'+url+'"><span class="tag is-success is-small">'+ name+'</span></a>'
												}

											{% endfor %}

											 
											if (sw==0 && day<=last){
												if (col==start_day){
													tr.appendChild(td)
													sw=1
													day++
												}
												else{
													td.innerHTML=''
													tr.appendChild(td)
												}

											}
											else if (sw==1 && day<=last){
												tr.appendChild(td)
												day++						
											}
											else{
												td.innerHTML=''
												tr.appendChild(td)
												sw=1
												day++
											}
										}	
									
										table.appendChild(tr)

								}

								return table
							}

						</script>

							{% else %}

							<tbody>

								<tr class = "table-row">
									<td class = "has-text-centered">---Nothing to show---</td>
							 	</tr>
								
							</tbody>

							{% endif %}
					</div>
				</div>
			</div>




{% endblock %}

blueprints/communities/templates/communities/events/index.html
{% extends "communities-base.html" %}

{% block content %}
	<div class="notification gold">
		<div class="columns is-centered">
	        <div class="column search-box">
		  		<a href="" class="button viewbtn is-active">
					<span class="icon">
						<i class="fa fa-list"></i>
					</span>
				</a>
				&nbsp
				<a href="{{url_for('communities.events_calendar')}}" class="button viewbtn">
					<span class="icon">
						<i class="fa fa-calendar-alt"></i>
					</span>
				</a>
	        </div>

			<div class="column">
				<div class="tabs proposal is-toggle is-toggle-rounded has-text-weight-bold is-centered">
				  <ul>
				    <li {% if status=='all' %} class="is-active" {% endif %}>
				      <a href="{{url_for('communities.events', status='all', page='1', search=search)}}">
				        <span class="icon is-small"><i class="fas fa-list-ul" aria-hidden="true"></i></span>
				        <span class="proposal">All</span>
				      </a>
				    </li>
				    <li {% if status=='scheduled' %} class="is-active" {% endif %}>
				      <a href="{{url_for('communities.events', status='scheduled', page='1', search=search)}}">
				        <span class="icon is-small"><i class="fas fa-calendar-alt" aria-hidden="true"></i></span>
				        <span class="proposal">Scheduled</span>
				      </a>
				    </li>
				    <li {% if status=='finished' %} class="is-active" {% endif %}>
				      <a href="{{url_for('communities.events', status='finished', page='1', search=search)}}">
				        <span class="icon is-small"><i class="fas fa-calendar-check" aria-hidden="true"></i></span>
				        <span class="proposal">Finished</span>
				      </a>
				    </li>
				  </ul>
				</div>
			</div>

			<div class="column search-box">
				<div class="field is-pulled-right has-addons has-addons-centered">
					<div class="control">
						<form action="" method="POST">
						{{form.hidden_tag()}}
				    		{{form.search(class_='input', placeholder='Search')}}
					</div>
					<p class="control">
				     	{{form.submit(class_='button search')}}
					</p>
					</form>
				</div>
			</div>
      	</div>
	</div>

	<div class="columns is-gapless">

		<div class="column">
			<div class="card-header search-show">
				<p class="card-header-title">
					<span class="fas fa-poll-h"></span>&nbsp;
					{% if search!=' ' %}
					You searched for &nbsp;
					<span class="search-highlight">
						&nbsp;'{{search}}'
						<a href="{{url_for('communities.events', status='all', page='1', search=' ')}}"><span class="fas fa-times-circle"></span></a>&nbsp;
					</span>
					&nbsp; in
					{% endif %}Events
				</p>
				<div class="is-pulled-right">
					<p class="card-header-title">
						Total: {{events.total}}
					</p>
				</div>
			</div>
			<div class="columns padding-el is-multiline">
				{% if events.items %}

						{% for event in events.items %}
							{% include 'communities/events/_events.html' %}
						{% endfor %}

					{% else %}
					<table class="table is-fullwidth">
						<thead></thead>
					<tbody>

						<tr class = "table-row">
							<td class="has-text-centered">
								<div class='field has-text-centered'>
									<span class='tag is-warning is-large'>No results found</span>
								</div>
							</td>
					 	</tr>
						
					</tbody>
				</table>

				{% endif %}	
			</div>
		</div>	
	</div>
	{% if events.pages>1 %}
        <div class="card-content">
	<nav class="pagination" role="navigation" aria-label="pagination">
		<a class="pagination-previous"  {% if events.has_prev %}  href="{{url_for('communities.events', search=search, page=events.prev_num|string)}}"{% else %} disabled {% endif %}>Previous</a>
		<a class="pagination-next" {% if events.has_next %} href="{{url_for('communities.events', search=search, page=events.next_num|string)}}" {% else %} disabled {% endif %}>Next page</a>
		<ul class="pagination-list">
			Page {{events.page}} of {{events.pages}}
		</ul>
	</nav>
</div>
	{% endif %}
{% endblock %}